apiVersion: v1 
kind: Service
metadata:
  name: service-backend
  labels:
        app: deployment-backend
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: pod-backend
  type: ClusterIP